import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const categories = [
  { slug: 'pilaf', emoji: '🍚', nameUz: 'Osh', nameRu: 'Плов', nameEn: 'Pilaf', sortOrder: 1 },
  { slug: 'manti', emoji: '🥟', nameUz: 'Manti', nameRu: 'Манты', nameEn: 'Manti', sortOrder: 2 },
  { slug: 'shashlik', emoji: '🍢', nameUz: 'Shashlik', nameRu: 'Шашлык', nameEn: 'Shashlik', sortOrder: 3 },
  { slug: 'lagman', emoji: '🍜', nameUz: 'Lag\'mon', nameRu: 'Лагман', nameEn: 'Lagman', sortOrder: 4 },
  { slug: 'samsa', emoji: '🥙', nameUz: 'Somsa', nameRu: 'Самса', nameEn: 'Samsa', sortOrder: 5 },
  { slug: 'salads', emoji: '🥗', nameUz: 'Salatlar', nameRu: 'Салаты', nameEn: 'Salads', sortOrder: 6 },
  { slug: 'desserts', emoji: '🍰', nameUz: 'Shirinliklar', nameRu: 'Десерты', nameEn: 'Desserts', sortOrder: 7 },
  { slug: 'tea', emoji: '🍵', nameUz: 'Choy', nameRu: 'Чай', nameEn: 'Tea', sortOrder: 8 },
  { slug: 'drinks', emoji: '🥤', nameUz: 'Ichimliklar', nameRu: 'Напитки', nameEn: 'Drinks', sortOrder: 9 },
]

const products = [
  {
    slug: 'oshpalov-tashkent',
    categorySlug: 'pilaf',
    nameUz: 'Toshkent oshi',
    nameRu: 'Ташкентский плов',
    nameEn: 'Tashkent Pilaf',
    descriptionUz: 'An\'anaviy o\'zbek oshi — sabzi, go\'sht va ziravorlar bilan.',
    descriptionRu: 'Традиционный узбекский плов с морковью, мясом и специями.',
    descriptionEn: 'Traditional Uzbek pilaf with carrots, meat and spices.',
    ingredientsUz: 'Guruch, mol go\'shti, sabzi, piyoz, ziravorlar',
    ingredientsRu: 'Рис, говядина, морковь, лук, специи',
    ingredientsEn: 'Rice, beef, carrots, onion, spices',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684fc097d39b?w=800&q=80',
    price: 65000,
    weight: '450g',
    calories: 680,
    cookingTime: 35,
    isPopular: true,
    isChefPick: true,
  },
  {
    slug: 'oshpalov-qozon',
    categorySlug: 'pilaf',
    nameUz: 'Qozon oshi',
    nameRu: 'Казан-плов',
    nameEn: 'Kazan Pilaf',
    descriptionUz: 'Katta qozonda pishirilgan boy va xushbo\'y osh.',
    descriptionRu: 'Сытный ароматный плов, приготовленный в казане.',
    descriptionEn: 'Rich aromatic pilaf cooked in a traditional kazan.',
    ingredientsUz: 'Guruch, qo\'y go\'shti, sabzi, no\'xat',
    ingredientsRu: 'Рис, баранина, морковь, нут',
    ingredientsEn: 'Rice, lamb, carrots, chickpeas',
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80',
    price: 72000,
    weight: '500g',
    calories: 720,
    cookingTime: 40,
    isPopular: true,
  },
  {
    slug: 'manti-qovurma',
    categorySlug: 'manti',
    nameUz: 'Qovurma manti',
    nameRu: 'Жареные манты',
    nameEn: 'Pan-fried Manti',
    descriptionUz: 'Qo\'lda yopilgan manti — qovurilgan va bug\'da pishirilgan.',
    descriptionRu: 'Ручные манты — обжаренные и приготовленные на пару.',
    descriptionEn: 'Hand-folded manti — pan-fried and steamed.',
    ingredientsUz: 'Xamir, mol go\'shti, piyoz, ziravorlar',
    ingredientsRu: 'Тесто, говядина, лук, специи',
    ingredientsEn: 'Dough, beef, onion, spices',
    imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b0678c8?w=800&q=80',
    price: 48000,
    weight: '350g',
    calories: 420,
    cookingTime: 25,
    isChefPick: true,
  },
  {
    slug: 'shashlik-qiyma',
    categorySlug: 'shashlik',
    nameUz: 'Qiyma shashlik',
    nameRu: 'Шашлык из фарша',
    nameEn: 'Minced Shashlik',
    descriptionUz: 'Ko\'mir ustida pishirilgan nozik qiyma shashlik.',
    descriptionRu: 'Нежный шашлык из фарша на углях.',
    descriptionEn: 'Tender minced shashlik grilled over charcoal.',
    ingredientsUz: 'Mol go\'shti, piyoz, ziravorlar',
    ingredientsRu: 'Говядина, лук, специи',
    ingredientsEn: 'Beef, onion, spices',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80',
    price: 55000,
    weight: '300g',
    calories: 380,
    cookingTime: 20,
    isSpicy: true,
    isPopular: true,
  },
  {
    slug: 'lagman-uyghur',
    categorySlug: 'lagman',
    nameUz: 'Uyghur lag\'moni',
    nameRu: 'Уйгурский лагман',
    nameEn: 'Uyghur Lagman',
    descriptionUz: 'Qo\'lda tortilgan lag\'mon — sabzavot va go\'sht bilan.',
    descriptionRu: 'Лагман ручной лапши с овощами и мясом.',
    descriptionEn: 'Hand-pulled noodles with vegetables and meat.',
    ingredientsUz: 'Lag\'mon, go\'sht, sabzavot, sous',
    ingredientsRu: 'Лапша, мясо, овощи, соус',
    ingredientsEn: 'Noodles, meat, vegetables, sauce',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80',
    price: 52000,
    weight: '400g',
    calories: 520,
    cookingTime: 30,
    isPopular: true,
  },
  {
    slug: 'samsa-tandir',
    categorySlug: 'samsa',
    nameUz: 'Tandir somsa',
    nameRu: 'Самса из тандыра',
    nameEn: 'Tandoor Samsa',
    descriptionUz: 'Tandirda pishirilgan xirillagan somsa.',
    descriptionRu: 'Хрустящая самса из тандыра.',
    descriptionEn: 'Crispy samsa baked in a tandoor.',
    ingredientsUz: 'Xamir, qo\'y go\'shti, piyoz',
    ingredientsRu: 'Тесто, баранина, лук',
    ingredientsEn: 'Dough, lamb, onion',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80',
    price: 18000,
    weight: '180g',
    calories: 290,
    cookingTime: 15,
    isPopular: true,
  },
  {
    slug: 'achichuk-salad',
    categorySlug: 'salads',
    nameUz: 'Achichuk',
    nameRu: 'Ачичук',
    nameEn: 'Achichuk Salad',
    descriptionUz: 'Yangi pomidor, piyoz va ko\'katlar salati.',
    descriptionRu: 'Салат из свежих помидоров, лука и зелени.',
    descriptionEn: 'Fresh tomato, onion and herb salad.',
    ingredientsUz: 'Pomidor, piyoz, ko\'katlar',
    ingredientsRu: 'Помидоры, лук, зелень',
    ingredientsEn: 'Tomatoes, onion, herbs',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    price: 22000,
    weight: '200g',
    calories: 80,
    cookingTime: 5,
    isVegetarian: true,
  },
  {
    slug: 'halva-dessert',
    categorySlug: 'desserts',
    nameUz: 'Halvo',
    nameRu: 'Халва',
    nameEn: 'Halva',
    descriptionUz: 'An\'anaviy o\'zbek halvosi — yong\'oq bilan.',
    descriptionRu: 'Традиционная узбекская халва с орехами.',
    descriptionEn: 'Traditional Uzbek halva with nuts.',
    ingredientsUz: 'Un, yog\'och yong\'og\'i, asal',
    ingredientsRu: 'Мука, грецкий орех, мёд',
    ingredientsEn: 'Flour, walnuts, honey',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    price: 28000,
    weight: '150g',
    calories: 340,
    cookingTime: 0,
    isVegetarian: true,
  },
  {
    slug: 'green-tea',
    categorySlug: 'tea',
    nameUz: 'Yashil choy',
    nameRu: 'Зелёный чай',
    nameEn: 'Green Tea',
    descriptionUz: 'An\'anaviy choyxona yashil choyi — issiq va xushbo\'y.',
    descriptionRu: 'Традиционный зелёный чай чайханы — горячий и ароматный.',
    descriptionEn: 'Traditional tea house green tea — hot and fragrant.',
    ingredientsUz: 'Yashil choy barglari',
    ingredientsRu: 'Листья зелёного чая',
    ingredientsEn: 'Green tea leaves',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
    price: 12000,
    weight: '500ml',
    calories: 5,
    cookingTime: 5,
    isVegetarian: true,
    isSpecial: true,
  },
  {
    slug: 'ayran',
    categorySlug: 'drinks',
    nameUz: 'Ayron',
    nameRu: 'Айран',
    nameEn: 'Ayran',
    descriptionUz: 'Sovuq va tetiklantiruvchi an\'anaviy ichimlik.',
    descriptionRu: 'Холодный освежающий традиционный напиток.',
    descriptionEn: 'Cold refreshing traditional drink.',
    ingredientsUz: 'Qatiq, suv, tuz',
    ingredientsRu: 'Кефир, вода, соль',
    ingredientsEn: 'Yogurt, water, salt',
    imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=800&q=80',
    price: 15000,
    weight: '400ml',
    calories: 90,
    cookingTime: 0,
    isVegetarian: true,
  },
  {
    slug: 'non-bread',
    categorySlug: 'pilaf',
    nameUz: 'Tandir non',
    nameRu: 'Лепёшка из тандыра',
    nameEn: 'Tandoor Bread',
    descriptionUz: 'Yangi pishirilgan issiq tandir non.',
    descriptionRu: 'Свежая горячая лепёшка из тандыра.',
    descriptionEn: 'Freshly baked hot tandoor bread.',
    ingredientsUz: 'Un, suv, tuz',
    ingredientsRu: 'Мука, вода, соль',
    ingredientsEn: 'Flour, water, salt',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
    price: 8000,
    weight: '250g',
    calories: 220,
    cookingTime: 10,
    isVegetarian: true,
    isPopular: true,
  },
  {
    slug: 'qurutob',
    categorySlug: 'pilaf',
    nameUz: 'Qurutob',
    nameRu: 'Курутоб',
    nameEn: 'Qurutob',
    descriptionUz: 'Non, qurut va sabzavot bilan milliy taom.',
    descriptionRu: 'Национальное блюдо с лепёшкой, курутом и овощами.',
    descriptionEn: 'National dish with bread, qurut and vegetables.',
    ingredientsUz: 'Non, qurut, pomidor, piyoz',
    ingredientsRu: 'Лепёшка, курут, помидоры, лук',
    ingredientsEn: 'Bread, qurut, tomatoes, onion',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
    price: 45000,
    weight: '380g',
    calories: 410,
    cookingTime: 15,
    isVegetarian: true,
    isChefPick: true,
  },
]

async function main() {
  await prisma.orderItem.deleteMany()
  await prisma.order.deleteMany()
  await prisma.review.deleteMany()
  await prisma.favorite.deleteMany()
  await prisma.product.deleteMany()
  await prisma.category.deleteMany()
  await prisma.promoCode.deleteMany()
  await prisma.user.deleteMany()

  for (const cat of categories) {
    await prisma.category.create({ data: cat })
  }

  for (const p of products) {
    const category = await prisma.category.findUnique({ where: { slug: p.categorySlug } })
    if (!category) continue
    const { categorySlug, ...data } = p
    await prisma.product.create({
      data: { ...data, categoryId: category.id, galleryUrls: [p.imageUrl] },
    })
  }

  await prisma.promoCode.create({
    data: { code: 'SILKROAD10', discountPct: 10, isActive: true },
  })

  await prisma.restaurantSettings.upsert({
    where: { id: 'default' },
    create: {
      id: 'default',
      nameUz: 'Choyxona — Eski Shahar',
      nameRu: 'Чайхана — Старый Город',
      nameEn: 'Choyxona — Old City',
      phone: '+998 71 123 45 67',
      address: 'Toshkent, Eski Shahar, 12',
      latitude: 41.3111,
      longitude: 69.2797,
      openTime: '09:00',
      closeTime: '23:00',
      deliveryCost: 15000,
      instagramUrl: 'https://instagram.com/choyxona',
      telegramUrl: 'https://t.me/choyxona',
      isOpen: true,
    },
    update: {},
  })

  console.log('Seed complete')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
